api/urls.py
from django.urls import path
from .views import (
    ListPortfolioApiView,
    DetailPortfolioApiView,
)

app_name='api_portfolio'

urlpatterns = [
    path('', ListPortfolioApiView.as_view(), name='portfolio-list-api'),
    path('detail/<int:pk_field>/', DetailPortfolioApiView.as_view(), name='portfolio-detail-api'),

]

oline_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('api-auth/', include('rest_framework.urls')),

    path('', include('core.urls', namespace='portfolio')),
    path('sub/', include('portfolio.urls', namespace='portfolio_2')),
    path('api-portfolio/', include('api.urls', namespace='api_portfolio')),
    path('account/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


portfolio/urls.py
from django.urls import path

from .views import (
    HomeView,
    PortfolioView,
    PortfolioDetailView,
    ContactView,


    portfolio_form,
    student_info_form,
)

app_name='portfolio_2'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('portfolio/', PortfolioView.as_view(), name='portfolio'),
    path('portfolio/detail/<int:pk>/', PortfolioDetailView.as_view(), name='portfolio-detail'),
    path('contact/', ContactView.as_view(), name='contact'),


    path('portfolio/form/', portfolio_form, name='portfolio-form'),
    path('student/form/', student_info_form, name='student-form'),
]

portfolio/models.py
from django.db import models
from django.utils.translation import ugettext as _
from phonenumber_field.modelfields import PhoneNumberField

from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.


class Resume(models.Model):
    user     = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_resume')
    image    = models.ImageField(_("Your Image"), upload_to='student-image/', blank=True, null=True)
    bg_image = models.ImageField(_("Background Image"), upload_to='bg-image/', blank=True, null=True)
    career   = models.CharField(_("Career"), max_length=500, )
    about_me = models.TextField(_("About Me"), )

    class Meta:
        verbose_name = _("Resume")
        verbose_name_plural = _("Resumes")

    def __str__(self):
        return self.user.full_name + " | " + str(self.user.phone_number)


class Education(models.Model):
    user     = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_education')
    start_at = models.DateField(_("Start Date"),)
    end_at   = models.DateField(_("End Date"), blank=True, null=True)
    otm_or_place_of_education = models.CharField(_("Institution/Place of Education"), max_length=300,)
    faculty_or_subject        = models.CharField(_("Faculty/Subject"), max_length=300)     
    learned_skill             = models.TextField(_("Learned Skills"),)

    class Meta:
        verbose_name = _("Education")
        verbose_name_plural = _("Educations")

    def __str__(self):
        return self.user.full_name + " | " + str(self.user.phone_number)


class Experience(models.Model):
    user          = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_experience')
    company       = models.CharField(_("Company Name"), max_length=200)
    occpation     = models.TextField(_('Occupation'), max_length=300)
    qualification = models.TextField(_('Qualification'),)

    start_at = models.DateField(_('Start Date'),)
    end_at   = models.DateField(_('End Date'), blank=True, null=True)

    link     = models.URLField(_('Company Web Site Link'), blank=True, null=True)
    address  = models.CharField(_("Address"), max_length=300, blank=True, null=True)
    phone_number = PhoneNumberField(_("Company Phone-Number"), blank=True, null=True)

    class Meta:
        verbose_name = _("Experience")
        verbose_name_plural = _("Experiences")

    def __str__(self):
        return self.user.full_name + " | " + str(self.user.phone_number)


class Portfolio(models.Model):
    user        = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_portfolio')
    image       = models.ImageField(_("Cover Image"), upload_to='portfolio-cover-image/', blank=True, null=True)
    name        = models.CharField(_("Name"), max_length=300, blank=True, null=True)
    short_desc  = models.TextField(_('Short Description'), blank=True, null=True)
    description = models.TextField(_('Description'), blank=True, null=True)
    link        = models.URLField(_("Project Link"), blank=True, null=True)

    file        = models.FileField(_("Project File"), upload_to='project-file/', blank=True, null=True)
    document    = models.FileField(_("Project Document"), upload_to='project-document/', blank=True, null=True)

    class Meta:
        verbose_name = _("Portfolio")
        verbose_name_plural = _("Portfolios")

    def __str__(self):
        return self.user.full_name + " | " + str(self.user.phone_number)

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url=''
        return url


class Image(models.Model):
    portfolio = models.ForeignKey(Portfolio, on_delete=models.CASCADE, related_name='portfolio_image')
    image     = models.ImageField(_("Image"), upload_to="portfolio-image/", blank=True, null=True)
    caption   = models.CharField(_('Caption'), max_length=300, blank=True, null=True)

    class Meta:
        verbose_name = _("Image")
        verbose_name_plural = _("Image")

    def __str__(self):
        return self.portfolio.name
    
    @property
    def imageURL(self):
        try:
            url = self.image
        except:
            url=''
        return url


portfolio/forms.py
from django import forms
from django.db import models
from django.forms.widgets import Textarea
from tinymce.widgets import TinyMCE
from phonenumber_field.formfields import PhoneNumberField

from .models import (
    Resume,
    Education,
    Experience,
    Portfolio,
    Image,
)



class ResumeForm(forms.Form):
    user    = forms.CharField(widget=forms.TextInput(attrs={'type':"text", 'id':"student_id", 'value':'', 'style':"width: 100%;", 'name':'student'}))
    image   = forms.ImageField(widget=forms.FileInput(attrs={'type':"file", 'id':"yourimage", 'style':"width: 100%;", 'name':'image'}))
    bg_image= forms.ImageField(widget=forms.FileInput(attrs={'type':"file", 'id':"bacgraundimage", 'style':"width: 100%;", 'name':'bg_image'}))
    career  = forms.CharField(widget=forms.TextInput(attrs={'type':"text", 'class':"form-control", 'id':'career', 'name':"career"}))
    about_me= forms.CharField(widget=forms.Textarea(attrs={'class':"form-control", 'id':'about_me', 'name':'about_me'}))


class EducationForm(forms.ModelForm):
    user     = forms.CharField(widget=forms.TextInput(attrs={}))
    start_at = forms.DateField(widget=forms.DateInput(attrs={}))
    end_at   = forms.CharField(widget=forms.TextInput(attrs={}))
    otm_or_place_of_education = forms.CharField(widget=forms.TextInput(attrs={}))
    faculty_or_subject        = forms.CharField(widget=forms.TextInput(attrs={}))
    learned_skill             = forms.CharField(widget=forms.TextInput(attrs={}))

    class Meta:
        model = Education
        fields='__all__'


class ExperienceForm(forms.ModelForm):
    user          = forms.CharField(widget=forms.TextInput(attrs={}))
    student       = forms.CharField(widget=forms.TextInput(attrs={}))
    company       = forms.CharField(widget=forms.TextInput(attrs={}))
    occpation     = forms.CharField(widget=forms.TextInput(attrs={}))
    qualification = forms.CharField(widget=forms.Textarea(attrs={}))
    start_at      = forms.DateField(widget=forms.DateInput(attrs={}))
    end_at        = forms.DateField(widget=forms.DateInput(attrs={}))
    link          = forms.URLField(widget=forms.URLInput(attrs={}))
    address       = forms.CharField(widget=forms.TextInput(attrs={}))
    phone_number  = PhoneNumberField(widget=forms.TextInput(attrs={}))

    class Meta:
        model = Experience
        fields='__all__'


class PortfolioForm(forms.Form):
    user        = forms.CharField(widget=forms.TextInput(attrs={'type':"hidden", 'id':"user", 'value':'', 'style':"width: 100%;", 'name':'user'}))
    name        = forms.CharField(widget=forms.TextInput(attrs={'type':"text", 'class':"form-control", 'id':'name', 'name':"name"}))
    image       = forms.ImageField(widget=forms.FileInput(attrs={'type':"file", 'id':"image", 'style':"width: 100%;", 'name':'image'}))
    link        = forms.URLField(widget=forms.URLInput(attrs={'type':"text", 'class':"form-control", 'id':'link', 'name':"link"}))
    short_desc  = forms.CharField(widget=Textarea(attrs={'id':'short_desc', 'class':"form-control", 'name':'short_desc'}))
    description = forms.CharField(widget=Textarea(attrs={ 'id':'description',  'class':"form-control", 'name':"description"}))

    file       = forms.FileField(widget=forms.FileInput(attrs={'type':"file", 'id':"file", 'style':"width: 100%;", 'name':'file', },), required=False)
    document   = forms.FileField(widget=forms.FileInput(attrs={'type':"file", 'id':"document", 'style':"width: 100%;", 'name':'document'}), required=False)

    # class Meta:
    #     model = Portfolio
    #     fields='__all__'

class ContactForm(forms.Form):
	full_name    = forms.CharField(max_length=100, widget=forms.TextInput(
        attrs={ 'type':"text", 'id':"exampleInputFullName1", 'name':"exampleInputFullName1", 'class':"form-control", 'placeholder': 'Dovurov Jamshid'}))
	phone_number = PhoneNumberField(widget=forms.TextInput(
        attrs={'type':"text", 'id':"exampleInputPhoneNumber", 'class':"form-control", 'placeholder': "+998 -- --- -- --"}))
	email        = forms.EmailField(widget=forms.EmailInput(
        attrs={'type':"text", 'id':"exampleInputEmail1", 'name':"exampleInputEmail1", 'class':"form-control",  'placeholder': "example@gmail.com"}))
	text         = forms.CharField(widget=forms.Textarea(
        attrs={'class':"form-control", 'id':'exampleInputText', 'name':'exampleInputText',  "placeholder" : "Xabaringizni/savolingizni yozing"}))


"""

<!-- Creating user instance by passing requested user id -->
    <script>
        var user_id = "{{ request.user.id }}";
        document.getElementById('username').value=user_id;
    </script>
<!-- end -->

"""

portfolio/views.py
from django.core.paginator import Paginator
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404, JsonResponse, BadHeaderError
from django.core import serializers
from django.views import View
from django.core.serializers.json import DjangoJSONEncoder
from django.template import defaultfilters
from django.conf import settings
from django.core.mail import send_mail
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.db.models import Case, Value, When, Q, F
import json

from django.contrib.auth import get_user_model
User = get_user_model()

from users.models import Student

from .forms import(
	ResumeForm,
	PortfolioForm,
	ContactForm,
)
from .models import (
	Resume,
	Education,
	Experience,
	Portfolio,
	Image,
)

# Create your views here.

class HomeView(View):
	template_name='portfolio/index.html'
	def get(self, request, *args, **kwargs):
		context={}
		return render(request, self.template_name, context)

class PortfolioView(View):
	template_name='portfolio/portfolio.html'
	def get(self, request, *args, **kwargs):
		object_list = Portfolio.objects.all()
		user=None
		if object_list:
			for obj in object_list:
				user = obj.user
		else:
			user="new"
		context={"object_list": object_list, 'user':user}
		return render(request, self.template_name, context)


class PortfolioDetailView(View):
	template_name='portfolio/portfolio-detail.html'
	def get(self, request, pk, *args, **kwargs):
		obj = Portfolio.objects.get(pk=pk)
		print(obj)
		context={'object':obj}
		return render(request, self.template_name, context)


class ContactView(View):
	template_name='portfolio/contact.html'
	def get(self, request, *args, **kwargs):
		form=ContactForm()
		context={'form':form}
		return render(request, self.template_name, context)
	
	def post(self, request, *args, **kwargs):
		form=ContactForm()
		context={'form':form}
		return render(request, self.template_name, context)


@login_required
def portfolio_form(request):
	if request.method == 'POST':
		form = PortfolioForm(request.POST, request.FILES)
		if form.is_valid():
			print("hello")
			print(form.cleaned_data.get('user'))
			print(form.cleaned_data.get('name'))
			print(form.cleaned_data.get('image'))
			print(form.cleaned_data.get('link'))
			print(form.cleaned_data.get('short_desc'))
			print(form.cleaned_data.get('description'))

			user = User.objects.get(pk=form.cleaned_data.get('user'))
			Portfolio.objects.create(
				user        = user,
				name        = form.cleaned_data.get('name'),
				image       = form.cleaned_data.get('image'),
				link        = form.cleaned_data.get('link'),
				short_desc  = form.cleaned_data.get('short_desc'),
				description = form.cleaned_data.get('description'),
				file        = form.cleaned_data.get('file'),
				document    = form.cleaned_data.get('document'),
			)
		else:
			for msg in form.errors:
				messages.error(request, f"{msg}: {form.errors[msg]}")

	return redirect('portfolio_2:portfolio')


def student_info_form(request):
	if request.method == 'POST':
		form = ResumeForm(request.POST, request.FILES)
		if form.is_valid():
			user = User.objects.get(pk=form.cleaned_data.get('student'))
			student = Student.objects.get(student=user)
			Resume.objects.create(
				student = student,
				image = form.cleaned_data.get('image'),
				bg_image = form.cleaned_data.get('bg_image'),
				career = form.cleaned_data.get('career'),
				about_me = form.cleaned_data.get('about_me'),
			)
		else:
			for msg in form.errors:
				messages.error(request, f"{msg}: {form.errors[msg]}")

	return redirect('portfolio_2:home')

templates/portfolio/base.html
{% load static %}
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        {% block css %}
        
        {% endblock css %}

        {% block title %}
            
        {% endblock title %}

    </head>

    <body>

        {% block body %}
        
        {% endblock body %}

        {% block js %}
        
        {% endblock js %}

    </body>

</html>

templates/portfolio/contact.html
{% extends "portfolio/base.html" %}
{% load static %}


    {% block css %}
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css"
        integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'bootstrap-4.5.3-dist/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock css %}


    {% block title %}
        <title>Aloqa</title>
    {% endblock title %}



    {% block body %}

        {% include 'portfolio/includes/navbar.html' %}

        {% include 'portfolio/includes/message.html' %}
        <section class="container" style="margin-top: 50px; margin-bottom: 100px;">
        <div class="row">
            <div class="col-10 col-sm-8 col-md-7 col-lg-5 m-auto">
                <div class="">
                    <form action="" method='POST' >
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        <div class="form-group">
                            <label for="exampleInputFullName1">FISH</label>
                            {{ form.full_name.errors }}
                            {{ form.full_name }}
                            <!-- <input type="text" id="exampleInputFullName1" name="exampleInputFullName1" class="form-control"> -->
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Elektron Pochta</label>
                            {{ form.email.errors }}
                            {{ form.email }}
                            <!-- <input type="text" id="exampleInputEmail1" name="exampleInputEmail1" class="form-control"> -->
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPhoneNumber">Telefon Raqam</label>
                            {{ form.phone_number.errors }}
                            {{ form.phone_number }}
                            <!-- <input type="text" id="exampleInputPhoneNumber" class="form-control"> -->
                        </div>
                        <div class="form-group">
                            <label for="exampleInputText">Xabar</label>
                            {{ form.text.errors }}
                            {{ form.text }}
                            <!-- <textarea  class="form-control" id='exampleInputText' name='exampleInputText' ></textarea> -->
                        </div>
                        <button class="btn btn-primary my-3 py-2" type='submit' style="border-radius: 20px; width: 100%;">Yuborish</button>
                    </form>
                </div>
            </div>
        </div>
    </section>

        {% include 'portfolio/includes/footer.html' %}

    {% endblock body %}


    {% block js %}
        
        <script src="{% static 'bootstrap-4.5.3-dist/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'bootstrap-4.5.3-dist/popper.js' %}"></script>
        <script src="{% static 'bootstrap-4.5.3-dist/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/index.js' %}" async defer></script>
    
    {% endblock js %}

templates/portfolio/portfolio-form.html
{% extends "portfolio/base.html" %}
{% load static %}


    {% block css %}
        
    {% endblock css %}


    {% block title %}
        <title>Portfolio Form</title>
    {% endblock title %}



    {% block body %}

        {% include 'portfolio/includes/navbar.html' %}

        {% include 'portfolio/includes/navbar.html' %}
                


        {% include 'portfolio/includes/footer.html' %}

    {% endblock body %}


    {% block js %}
        
    {% endblock js %}

templates/portfolio/portfolio.html
{% extends "portfolio/base.html" %}
{% load static %}


    {% block css %}

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css"
    integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'bootstrap-4.5.3-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

<style>
 
 .quote-imgs-thumbs {
  background: #eee;
  border: 1px solid #ccc;
  border-radius: 0.25rem;
  margin: 1.5rem 0;
  padding: 0.75rem;
}
.quote-imgs-thumbs--hidden {
  display: none;
}
.img-preview-thumb {
  background: #fff;
  border: 1px solid #777;
  border-radius: 0.25rem;
  box-shadow: 0.125rem 0.125rem 0.0625rem rgba(0, 0, 0, 0.12);
  margin-right: 1rem;
  max-width: 40px;
  padding: 0.25rem;
}

</style>
    
    {% endblock css %}


    {% block title %}
        <title>Portfolio</title>
    {% endblock title %}



    {% block body %}

        {% include 'portfolio/includes/navbar.html' %}

        {% include 'portfolio/includes/message.html' %}
                
            <section class="container" style="min-height: 500px;">
                <h4 class="text-center " style="margin-top: 30px; margin-bottom: 30px; color: grey;">
                    Portfoliolar To'plami
                </h4>
                    <hr class="" style="box-shadow: 0 0 10px 1px rgba(0,0,0,1) ;">
                <div class="row d-flex justify-content-around">
                    {% for obj in object_list %}
                        <div class="col-12 col-md-6 col-lg-6 col-xl-4 mb-3">
                            <div class="card card_img">
                                <img src="{{ obj.imageURL }}" alt="" style="width: 328px; height: 205px">
                                <div class="card_img_title d-flex justify-content-center text-center">
                                    <div class="card_img_title_1 p-3" style="">
                                        <h6 class="" style="color: aqua;">{{ obj.name }}</h6>
                                        <p class="" style="color:white;">
                                            {{ obj.short_desc|safe|truncatechars:70 }}
                                        </p>
                                    </div>
                                    <div class="card_img_title_2">
                                        <a class="btn" href="{{ obj.link }}" style="border-radius: 3px; background: linear-gradient(to right,rgb(62, 212, 212), teal);" >proyektni ko'rish</a>
                                        <a class="btn" href="{% url 'portfolio_2:portfolio-detail' obj.pk %}" style="border-radius: 3px; background: linear-gradient(to right,rgb(62, 212, 212), teal);">ko'proq malumot</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% empty %}
                        <div>
                            <h4>Bo'sh</h4>
                        </div>    
                    {% endfor %}

                    {% if request.user.is_authenticated %}
                        {% if request.user.id == user.id %}
                            <div class="col-12 col-md-6 col-lg-6 col-xl-4 mb-3">
                                <div class="card card_button">
                                    <img src="{% static 'image/white_bg.jpg' %}" alt="" style="width: 328px; height: 205px">
                                    <div class="card_button_img">
                                        <button class="btn btn-outline-dark" data-toggle="modal" data-target="#exampleModal">protfolio qo'shish</button>
                                    </div>
                                </div>
                            </div>
                        {% elif user == "new" %}
                            <div class="col-12 col-md-6 col-lg-6 col-xl-4 mb-3">
                                <div class="card card_button">
                                    <img src="{% static 'image/white_bg.jpg' %}" alt="" style="width: 328px; height: 205px">
                                    <div class="card_button_img">
                                        <button class="btn btn-outline-dark" data-toggle="modal" data-target="#exampleModal">protfolio qo'shish</button>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% endif %}

                </div>
            </section>


            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">Portfolio form</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                        <form method='post' enctype="multipart/form-data" action="{% url 'portfolio_2:portfolio-form' %}">
                            {% csrf_token %}
                            <input type="hidden" id="user" value='' style="width: 100%;" name='user'>
                            <div class="form-group my-1">
                                <label for="name">Nomi</label>
                                <input type="text" class="form-control" id='name' name="name">
                            </div> 

                            <div class="form-group my-1">
                                <label for="short_desc">Qisqacha Malumot</label>
                                <textarea id='short_desc' class="form-control" name='short_desc'></textarea>
                                
                            </div>
                           
                            <div class="form-group my-1">
                                <label for="description" >To'liq Malumot</label>
                                <textarea id='description'  class="form-control" name="description"></textarea>
                            </div>
                            <div class="form-group my-1">
                                <label for="link">Proyekt Linki</label>
                                <input type="text" class="form-control" id='link' name="link">
                            </div>
                            <div class="custom-file mb-5">
                                <label for="file" class="m-0">Zip/RAR File</label>
                                <div class="btn m-0" style="width: 100%; background-color:gray;color:white;">  
                                    <input type="file" id="file" style="width: 100%;", name='file'>
                                </div>
                                <small>proyektni zip/rar formatda yuklang</small>
                            </div>
                            <br>
                            <div class="custom-file mb-5">
                                <label for="document" class="m-0">Dokument</label>
                                <div class="btn m-0" style="width: 100%; background-color:gray;color:white;">  
                                    <input type="file" id="document" style="width: 100%;", name='document'>
                                </div>
                            </div>
                            <div class="custom-file mb-5">
                                <label for="image" class="m-0">Asosiy Rasm</label>
                                <div class="btn m-0" style="width: 100%; background-color:gray;color:white;">  
                                    <input type="file" id="image" style="width: 100%;", name='image'>
                                </div>
                            </div>
                            <div class="custom-file mb-5">
                                <label for="upload_imgs" class="">Rasmlar</label>
                                <div class="btn m-0" style="width: 100%; background-color:gray;color:white;">
                                    <input type="file" id="upload_imgs" style="width: 100%;" name="upload_imgs[]" multiple />
                                </div>
                                <div class="quote-imgs-thumbs quote-imgs-thumbs--hidden" id="img_preview" aria-live="polite"></div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Yopish</button>
                                <button type="submit" class="btn btn-primary">Saqlash</button>
                            </div>
                        </form>
                        <script>
                            var user_id = "{{ request.user.id }}";
                            document.getElementById('user').value=user_id;
                        </script>
                    </div>
                </div>
            </div>
        </div>

        {% include 'includes/pagination.html' %}
            
        {% include 'portfolio/includes/footer.html' %}

    {% endblock body %}


    {% block js %}
        <script src="{% static 'bootstrap-4.5.3-dist/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'bootstrap-4.5.3-dist/popper.js' %}"></script>
        <script src="{% static 'bootstrap-4.5.3-dist/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/index.js' %}" async defer></script>
        <script src="https://cdn.ckeditor.com/ckeditor5/17.0.0/classic/ckeditor.js"></script>
        <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>

        <script>
            $('#myModal').on('shown.bs.modal', function () {
                $('#myInput').trigger('focus')
            })
        
            var imgUpload = document.getElementById('upload_imgs')
            , imgPreview = document.getElementById('img_preview')
            , imgUploadForm = document.getElementById('img-upload-form')
            , totalFiles
            , previewTitle
            , previewTitleText
            , img;

            imgUpload.addEventListener('change', previewImgs, false);
            imgUploadForm.addEventListener('submit', function (e) {
            e.preventDefault();
            alert('Images Uploaded! (not really, but it would if this was on your website)');
            }, false);

            function previewImgs(event) {
            totalFiles = imgUpload.files.length;
            
            if(!!totalFiles) {
                imgPreview.classList.remove('quote-imgs-thumbs--hidden');
                previewTitle = document.createElement('p');
                previewTitle.style.fontWeight = 'bold';
                previewTitleText = document.createTextNode(totalFiles + ' Total Images Selected');
                previewTitle.appendChild(previewTitleText);
                imgPreview.appendChild(previewTitle);
            }
            
            for(var i = 0; i < totalFiles; i++) {
                img = document.createElement('img');
                img.src = URL.createObjectURL(event.target.files[i]);
                img.classList.add('img-preview-thumb');
                imgPreview.appendChild(img);
            }
            }
        </script>
    {% endblock js %}

templates/portfolio/resume-form.html
{% extends "portfolio/base.html" %}
{% load static %}


    {% block css %}
        
    {% endblock css %}


    {% block title %}
        <title>Resume Form</title>
    {% endblock title %}



    {% block body %}

        {% include 'portfolio/includes/navbar.html' %}

        {% include 'portfolio/includes/navbar.html' %}
                


        {% include 'portfolio/includes/footer.html' %}

    {% endblock body %}


    {% block js %}
        
    {% endblock js %}