api/urls.py
from django.urls import path
from .views import (
    ListPortfolioApiView,
    DetailPortfolioApiView,
)

app_name='api_portfolio'

urlpatterns = [
    path('', ListPortfolioApiView.as_view(), name='portfolio-list-api'),
    path('detail/<int:pk_field>/', DetailPortfolioApiView.as_view(), name='portfolio-detail-api'),

]

core/urls.py
from django.urls import path

from .views import (
    HomeView, 
    PortfolioView,
    PortfolioDetailView,
    GuideView,


    FeedbackView,
)

app_name='portfolio'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('portfolio/', PortfolioView.as_view(), name='portfolio'),
    path('portfolio-detail/<int:pk>/', PortfolioDetailView.as_view(), name='portfolio-detail'),
    path('guide/', GuideView.as_view(), name='guide'),
    path('contact/', FeedbackView.as_view(), name='contact'),
]

oline_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('api-auth/', include('rest_framework.urls')),

    path('', include('core.urls', namespace='portfolio')),
    path('sub/', include('portfolio.urls', namespace='portfolio_2')),
    path('api-portfolio/', include('api.urls', namespace='api_portfolio')),
    path('account/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


templates/includes/footer.html
{% load static %}

<footer class="footer-section shadow-lg py-5 bg-primary">

    <div class="container">

        <div class="row ">

            <div class="col-sm-12 col-md-6 col-lg-3">
                <h4 class=" mb-4 text-white font-weight-bold"> 
                    <a class="navbar-brand" href="/"> 
                        <img class="rounded" src="https://wallpapercave.com/wp/wp7041166.jpg" width="30" height="30" alt="">
                         online PORTFOLIO
                    </a>
                </h4>

                <ul class="nav">

                    <li class="nav-item">
                        <a class="nav-link text-white" href="#"><i class="fab fa-facebook"></i></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="#"><i class="fab fa-twitter"></i></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="#"><i class="fab fa-instagram"></i></a>
                    </li>

                </ul>
            </div>

            <div class="col-sm-12 col-md-6 col-lg-3">
                <ul class="nav flex-column ">
                    <li class="nav-item mb-3 ">
                        <p class="nav-link border-bottom  active" href="#">Bo'limlar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/">Asosiy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Portfolio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Yo'riqnoma</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Aloqa</a>
                    </li>

                </ul>
            </div>

            <div class="col-sm-12 col-md-6 col-lg-3">
                <ul class="nav flex-column ">
                    <li class="nav-item mb-3 ">
                        <p class="nav-link border-bottom  active" href="#">Biz Haqimizda</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Sayt Haqida</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Ishlar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Qo'llab Quvvatlash</a>
                    </li>
                </ul>
            </div>
            <div class="col-sm-12 col-md-6 col-lg-3">
                <ul class="nav flex-column ">
                    <li class="nav-item mb-3 ">
                        <p class="nav-link border-bottom  active" href="#">Aloqa Ma'lumotlari</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">info@onlineportfolio.uz</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">+99899-990-99-99</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">+99899-990-99-99</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">+99899-990-99-99</a>
                    </li>

                </ul>
            </div>


        </div>
    </div>

</footer>

templates/includes/message.html
{% if messages %}
    {% for message in messages %}
        <div class="alert_box alert alert-{{ message.tags }}" role="alert" >
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/includes/navbar.html
{% load static %}

<nav class="navbar navbar_box fixed-top shadow-lg navbar-expand-lg py-3  navbar-dark ">
    <div class="container">
        <a class="navbar-brand" href="/"> <img class="rounded" src="https://wallpapercave.com/wp/wp7041166.jpg" width="30" height="30" alt=""> online PORTFOLIO</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav m-auto">
                <li class="nav-item">
                    <a class="nav-link text-light" href="/">Asosiy</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" href="{% url 'portfolio:portfolio' %}">Portfolio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" href="{% url 'portfolio:guide' %}">Yo'riqnoma</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" href="{% url 'portfolio:contact' %}">Aloqa</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <form class="form-inline  my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="search" placeholder="Search"
                            aria-label="Search">
                        <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Qidiruv</button>
                    </form>
                </li>
                <li class="nav-item dropdown">
                    {% if request.user.is_authenticated %}
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ request.user.full_name }}
                        </a>
                    {% else %}
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: aliceblue;">
                        Start Account
                        </a>
                    {% endif %}
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if request.user.is_authenticated %}
                            <a class="dropdown-item" href="{% url 'portfolio_2:portfolio' %}">Mening Portfoliom</a>
                            <a class="dropdown-item" href="{% url 'logout' %}">Chiqish</a>
                        {% else %}
                            <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                            <a class="dropdown-item" href="{% url 'signup' %}">Registratsiya</a>
                        {% endif %}
                    </div>
                </li>    
            </ul>
        </div>    
    </div>      
</nav>  

templates/includes/navbar_2.html
{% load static %}

<nav class="navbar bg-primary fixed-top shadow-lg navbar-expand-lg py-3  navbar-dark ">
    <div class="container">
        <a class="navbar-brand" href="/"> <img class="rounded" src="https://wallpapercave.com/wp/wp7041166.jpg" width="30" height="30" alt=""> online PORTFOLIO</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav m-auto">
                <li class="nav-item">
                    <a class="nav-link text-light" href="/">Asosiy</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" href="{% url 'portfolio:portfolio' %}">Portfolio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" href="{% url 'portfolio:guide' %}">Yo'riqnoma</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" href="{% url 'portfolio:contact' %}">Aloqa</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <form class="form-inline  my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="search" placeholder="Search"
                            aria-label="Search">
                        <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Qidiruv</button>
                    </form>
                </li>
                <li class="nav-item dropdown">
                    {% if request.user.is_authenticated %}
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ request.user.full_name }}
                        </a>
                    {% else %}
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: aliceblue;">
                        Start Account
                        </a>
                    {% endif %}
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if request.user.is_authenticated %}
                            <a class="dropdown-item" href="{% url 'portfolio_2:portfolio' %}">Mening Portfoliom</a>
                            <a class="dropdown-item" href="{% url 'logout' %}">Chiqish</a>
                        {% else %}
                            <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                            <a class="dropdown-item" href="{% url 'signup' %}">Registratsiya</a>
                        {% endif %}
                    </div>
                </li>    
            </ul>
        </div>    
    </div>    
</nav>  

templates/includes/pagination.html
<div class="col-12 d-flex justify-content-center">   
    <ul class="pagination mt-4 ">
      <li class="page-item"><a class="page-link" href="#"><i class="fa fa-fa fa-arrow-left"></i></a></li>
      <li class="page-item"><a class="page-link" href="#">1</a></li>
      
      <li class="page-item"><a class="page-link" href="#"><i class="fa fa-arrow-right"></i></a></li>
    </ul>
</div>